# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IIFRXnyafP5U9Fo8WATvv-Ofszhortur
"""

import streamlit as st
import google.generativeai as genai

try:
  key = st.secrets['AIzaSyAAxthHR2ELFqS1Ugf0U9Kgq2QFY_eEu1U']
  genai.configure(api_key=key)
  model = genai.GenerativeModel('gemini-2.0-flash-lite')

  if "chat" not in st.sesstion_state:
    st.session_state.chat = model.start_chat(history=[])
  st.title('Gemini Pro Test')

  def role_to_streamlit(role:str) -> str:
    if role == 'model':
      return 'assistant'
    else:
      return role

  for message in st.session_state.chat.history:
    with st.chat_message(role_to_streamlit(message.role)):
      st.markdown(message.content)

  if prompt := st.chat_input('Text Here'):
    st.chat_message('user').markdown(prompt)
    response = st.session_state.chat.send_message(prompt)
    with st.chat_message('assistant'):
        st.markdown(response.content)
except Exception as e:
  st.error(f'An error occurred {e}')